### ISSUE TITLE
[QUESTION] Barricaded World Improvement

### ISSUE THREAD

**Issue by logitechQ** [Poltergeist-ix/TargetSquareOnLoad#1]
Could this mod be used in "Barricaded world"?
Or is that outside of the scope of this mod?
And if it's possible who can I turn to, to have it done.

I'm no programmer so I don't really understand this but I would love a version of that mod that just runs better

I'm not asking anyone to do the work for free
Just curious how much work it would be and if I could learn to just do it myself or if I better just commission someone

**Comment by Poltergeist-ix** [comment]
No, this mod would not help in this sotuation.

There will be a new Event added in v 42 that will benefit mods like the "Barricaded World".
